common: &common
  adapter: postgresql

development:
  <<: *common
  database: golf_development

test: &test
  <<: *common
  database: golf_test

production:
  <<: *common
  database: golf_production

cucumber:
  <<: *test
