GolfBall.create(brand: "Titleist", name: "ProV1", mini_description: "The Titleist Pro V1 utilizes a three-piece multi-layer construction to maximize distance, durability and performance. The Pro V1 golf ball is the best choice for most amateur golfers as it provides exceptional distance and short game scoring performance. This set includes 12 balls.", description: "The Titleist Pro V1 represents the coalescence of three of Titleist's industry leading technologies: large solid core, multi-component construction, and high performance Urethane Elastomer cover technology. Fast initial velocity, lower spin and high launch combine to produce a flatter, less arcing ascent and straight ball flight for exceptional driver and long iron distance. The trajectory profile of the New Titleist Pro V1 generates a steep angle of descent into the green and provides Drop-and-Stop performance on approach shots. The Titleist Pro V1x delivers very low driver and iron spin combined with very high speed. The result is exceptionally long distance and a straight flight, particularly for the game's hardest hitters.", year: "2012", original_price: "99.99", price: "65.99", image_path: "assets/titleist_500x488.png")

GolfBall.create(brand: "TaylorMade", name: "Lethal", mini_description: "Ultimate tour performance lethal golf ball. 5-Layer technology promotes optimum spin control off every club. Seamless LDP (low-drag performance) dimple pattern promotes the most penetrating flight of any taylormade ball. Sta-white cast-urethane cover material promotes optimum feel and tour-caliber spin. 
Progressive velocity provides outstanding velocity for any given swing speed.", description: "This ultimate tour performance lethal golf ball's revolutionary 5-Layer Construction, Progressive Velocity Technology and Seamless LDP 322 dimple pattern work in conjunction to promote game-changing performance. Lethal combines the most penetrating, wind-defying flight of any TaylorMade ball with the kind of greenside feel and spin that Tour professionals demand, making it the ultimate Tour performance ball.", year: "2012", original_price: "89.99", price: "55.99", image_path: "assets/taylormade_550x550.jpeg")

GolfBall.create(brand: "Nike", name: "20XI-X", mini_description: "Designed for golfers who want Tour level performance for 90 plus miles per hour swing speeds. Features include a radical new resin core, and a superior velocity, distance and control. The lighter, low density resin core distributes weight to the perimeter, increasing ball moment of inertia. Higher ball moment of inertia maintains spin after apex, adding yards and minimizing travel off line.", description: ".", year: "2012", original_price: "79.99", price: "45.99", image_path: "assets/nike_550x550.jpeg")

GolfBall.create(brand: "Callaway", name: "Hex Black", mini_description: "With features like enhanced durability, superior greenside spin and HEX Aerodynamics, the Callaway HEX Black Tour delivers six points of performance that help make this Callaway's most highly engineered Tour ball ever.", description: "The Callaway HEX Black Tour golf ball strikes the perfect balance of Tour performance for both the control freak and the distance-seeker. Engineered with a highly durable Urethane cover, it's designed for Optimized Tour Performance. The HEX Black Tour promotes a lower spin off the tee for increased distance in your long game and features high spin on approach shots for unparalleled control and ultimate stopping power into the green. From powerful ball speeds to a penetrating ball flight and soft feel, the HEX Black Tour golf balls offer the ultimate blend of Tour control and distance.", year: "2012", original_price: "69.99", price: "35.99", image_path: "assets/callaway_405x395.jpg")

GolfBall.create(brand: "Bridgestone", name: "B330-RX", mini_description: "The RXS is designed for players who prefer maximum Tour spin. Soft gradational compression core for longer and straighter distance. Reengineered mantle for reduced spin and greater accuracy. Very soft Urethane cover for players seeking extra greenside spin control. 330 dual dimple technology for a consistent flight.", description: "Tour Performance optimized for amateur swing speeds under 105 mph with a preference for maximum TOUR SPIN. The NEW B330-RXS offers a reformulated mantle and Dual Dimple Technology. The reformulated mantle offers reduced side spin for greater accuracy and distance while Bridgestone's proprietary Dual Dimple Technology delivers superior aerodynamics and enhanced wind performance. The B330-RXS continues to feature a soft core design that allows maximum compression for moderate swing speed players. It also features a softer Urethane cover than the B330-RX for increased greenside spin and control.", description: ".", year: "2012", original_price: "59.99", price: "25.99", image_path: "assets/bridgestone_350x400.jpg")
