GolfBall.create(brand: "Titleist", name: "ProV1", mini_description: "The Titleist Pro V1 utilizes a three-piece multi-layer construction to maximize distance, durability and performance. The Pro V1 golf ball is the best choice for most amateur golfers as it provides exceptional distance and short game scoring performance. This set includes 12 balls.", description: "The Titleist Pro V1 represents the coalescence of three of Titleist's industry leading technologies: large solid core, multi-component construction, and high performance Urethane Elastomer cover technology. Fast initial velocity, lower spin and high launch combine to produce a flatter, less arcing ascent and straight ball flight for exceptional driver and long iron distance. The trajectory profile of the New Titleist Pro V1 generates a steep angle of descent into the green and provides Drop-and-Stop performance on approach shots. The Titleist Pro V1x delivers very low driver and iron spin combined with very high speed. The result is exceptionally long distance and a straight flight, particularly for the game's hardest hitters.", year: "2012", original_price: "99.99", price: "65.99", image_path: "assets/titleist_500x488.png")

GolfBall.create(brand: "TaylorMade", name: "Lethal", description: "Best ball money can buy", year: "2012", original_price: "89.99", price: "55.99", image_path: "assets/taylormade_550x550.jpeg")

GolfBall.create(brand: "Nike", name: "20XI-X", description: "Best ball money can buy", year: "2012", original_price: "79.99", price: "45.99", image_path: "assets/nike_550x550.jpeg")

GolfBall.create(brand: "Callaway", name: "Hex Black", description: "Best ball money can buy", year: "2012", original_price: "69.99", price: "35.99", image_path: "assets/callaway_405x395.jpg")

GolfBall.create(brand: "Bridgestone", name: "8330-RX", description: "Best ball money can buy", year: "2012", original_price: "59.99", price: "25.99", image_path: "assets/bridgestone_350x400.jpg")
